---
- name: prepare hosts for Satellite registration
  hosts: "{{ idm_hosts }}"
  tasks:
    - name: unregister subscription and start fresh
      redhat_subscription:
        state: absent

    - name: install katello-ca-consumer-latest certificate
      command: yum localinstall -y http://sat-node.beniaris.com/pub/katello-ca-consumer-latest.noarch.rpm
      args:
        warn: no

- name: register infrastructure hosts to Satellite
  hosts: "{{ idm_hosts }}"
  tasks:
    - name: register {{ idm_hosts }} with activation key
      redhat_subscription:
        state: present
        activationkey: "{{ activation_key }}"
        org_id: Beniaris

    - name: install katello agent on the server
      yum:
        name: katello-agent
        state: latest

    - name: update server to latest patch level
      command: yum -y update
      args: 
        warn: no

