---
- name: Register infrastructure server to Satellite
  hosts: infservers
  tasks:
    - name: clean existing registration and start fresh
      redhat_subscription:
        state: absent

    - name: install katello-ca-consumer-latest certificate
      command: yum localinstall -y http://satellite.beniaris.com/pub/katello-ca-consumer-latest.noarch.rpm
      args:
        warn: no

    - name: register node to the Satellite server
      redhat_subscription:
        state: present
        activationkey: "ak_infservers_to_prod"
        org_id: Beniaris

    - name: install katello agent on the server
      yum:
        name: katello-agent
        state: latest

    - name: update server to latest patch level
      command: yum -y update
      args: 
        warn: no
                
    - name: restarted httpd service
      service:
        name: sshd
        enabled: yes
        state: started
        
