---
- name: Register infrastructure server to Satellite
  hosts: infrastructure
  tasks:
    - name: install katello-ca-consumer-latest certificate
      #command: rpm -Uvh http://sat-server.beniaris.com/pub/katello-ca-consumer-latest.noarch.rpm
      command: yum localinstall -y http://sat-server.beniaris.com/pub/katello-ca-consumer-latest.noarch.rpm
      ignore_errors: yes

    - name: register node to the Satellite server
      redhat_subscription:
        state: present
        activationkey: reg_inf_to_prod
        org_id: Beniaris

    - name: install katello agent on the server
      yum:
        name: katello-agent
        state: latest
