---
- name: prepare hosts for Satellite registration
  hosts: infservers eapservers
  tasks:
    - name: unregister subscription and start fresh
      redhat_subscription:
        state: absent

    - name: install katello-ca-consumer-latest certificate
      command: yum localinstall -y http://satellite.beniaris.com/pub/katello-ca-consumer-latest.noarch.rpm
      args:
        warn: no

- name: register infrastructure hosts to Satellite
  hosts: infservers
  tasks:
    - name: register infrastructure hosts with activation key
      redhat_subscription:
        state: present
        activationkey: "ak_infservers_to_prod"
        org_id: Beniaris

    - name: install katello agent on the server
      yum:
        name: katello-agent
        state: latest

    - name: update server to latest patch level
      command: yum -y update
      args: 
        warn: no

- name: register JBoss EAP hosts to Satellite
  hosts: eapservers
  tasks:
    - name: register infrastructure hosts with activation key
      redhat_subscription:
        state: present
        activationkey: "ak_eapservers_to_prod"
        org_id: Beniaris

    - name: install katello agent on the server
      yum:
        name: katello-agent
        state: latest

    - name: update server to latest patch level
      command: yum -y update
      args: 
        warn: no
